---
- name: Installing git, tig, unzip, tmux, jq
  apt: pkg=git,tig,unzip,tmux,jq state=latest
  become: true

- name: Creating new ~/.tmux.conf
  template:
    src: tmux.conf
    dest: ~/.tmux.conf

- name: Installing vim
  include: vim.yml

- name: Installing oh-my-zsh
  include: oh-my-zsh.yml

- name: Installing fzf
  include: fzf.yml
